In [7]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline
%config InlineBackend.figure_format = 'svg'

In [14]:
#1.Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [22]:
#2.Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.
a1 = a.reshape(2, 6)
a2 = a.reshape(3, 4)
a3 = a.reshape(4, 3)
a4 = a.reshape(6, 2)
a5 = a.reshape(12, 1)
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [23]:
#3.Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 
#(в трех примерах - для обозначения числа столбцов, в двух - для строк).
a1 = a.reshape(2, -1)
a2 = a.reshape(3, -1)
a3 = a.reshape(4, -1)
a4 = a.reshape(-1, 2)
a5 = a.reshape(-1, 1)
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [34]:
#4.Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?
a = np.arange(12, 24)
b = a.reshape(12, 1)
print(a)
print(b)
print(a.ndim, a.shape)
print(b.ndim, b.shape)
#массив Numpy, состоящий из одного столбца и 12 строк выводится как двумерный массив с дополнительными []. 
#Для получения данных из такого массива нам необходимо использовать индекс строки + индекс столбца. 
#Таким образом, массив Numpy, состоящий из одного столбца и 12 строк,  нельзя назвать одномерным, 
#что подтверждается с помощью атрибутов .ndim и .shape.

[12 13 14 15 16 17 18 19 20 21 22 23]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]
1 (12,)
2 (12, 1)


In [29]:
#5.Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой 
#из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. 
c = np.random.randn(3, 4)
print(c)

[[ 0.49320345  1.40631367 -1.51923785 -0.76312998]
 [ 0.02535485  0.87347843 -0.89649564  0.82450451]
 [ 0.07511289  0.12292812 -0.43321679  0.13225905]]


In [31]:
#Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.
print(c.size)
c = c.flatten()
print(c.size)

12
12


In [37]:
#6.Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [41]:
#7.Создать массив b, состоящий из 1 строки и 10 столбцов: 
#целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?
b = np.arange(20, 1, -2).reshape(1, 10)
b
#Разница между массивами a и b в том, что a - одномерный, а b - двумерный

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [45]:
#8.Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, 
#чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.
a = np.zeros((2, 2))
b = np.ones((3, 2))
v = np.vstack((a, b))
print(v)
print(v.size)

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
10


In [49]:
#9.Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. 
a = np.arange(0, 12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [50]:
#Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов.
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [51]:
#Получить матрицу At путем транспонирования матрицы A.
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [52]:
#Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения.
B = A.dot(At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [54]:
#Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?
print(B.size, B.shape)


16 (4, 4)


In [55]:
#Получится ли вычислить обратную матрицу для матрицы B и почему?
d = np.linalg.det(B)
d
#Обратную матрицу можно вычислить только для матрицы определитель которой НЕ РАВЕН 0. 

0.0

In [56]:
#10.Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.
np.random.seed(42)

In [63]:
#11.Создайте одномерный массив c, 
#составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 
c = np.random.randint(0, 16, 16)
c

array([12, 11,  8,  0, 10, 10, 14,  9, 15, 11, 11, 15, 14, 13, 13, 14])

In [67]:
#12.Поменяйте его форму так, чтобы получилась квадратная матрица C.
c = c.reshape(4, 4)
c

array([[12, 11,  8,  0],
       [10, 10, 14,  9],
       [15, 11, 11, 15],
       [14, 13, 13, 14]])

In [69]:
#Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. 
D = c * 10 + B
D


array([[125, 124, 103,  32],
       [114, 150, 226, 212],
       [173, 196, 259, 362],
       [172, 252, 342, 442]])

In [71]:
#Вычислите определитель, ранг и обратную матрицу D_inv для D.
d = np.linalg.det(D)
r = np.linalg.matrix_rank(D)
print(d)
print(r)

81895800.00000027
4


In [72]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.00015703,  0.00765607,  0.02306614, -0.02257478],
       [ 0.01433285, -0.0263845 , -0.02433629,  0.03154887],
       [-0.00681818,  0.02465035, -0.00028548, -0.01109581],
       [-0.00295717, -0.00700988,  0.00511992,  0.00164551]])

In [73]:
#13.Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. 
#Убедитесь, что в матрице D_inv остались только нули и единицы.
D_inv = np.where(D_inv<0, 0, 1)
D_inv

array([[1, 1, 1, 0],
       [1, 0, 0, 1],
       [0, 1, 0, 0],
       [0, 0, 1, 1]])

In [76]:
#С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, 
#получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, 
#должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv
#равен 0, должны быть равны соответствующему элементу матрицы C.
E = np.where(D_inv==1, B, c)
print(B)
print(c)
print(E)

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
[[12 11  8  0]
 [10 10 14  9]
 [15 11 11 15]
 [14 13 13 14]]
[[  5  14  23   0]
 [ 14  10  14 122]
 [ 15  86  11  15]
 [ 14  13 212 302]]
