In [1]:
#1. Импортируйте библиотеку Numpy и дайте ей псевдоним np
import numpy as np

In [13]:
#Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов.
#Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй — числа 6, 8, 11, 10, 7.
a = np.array([[1, 6],
             [2, 8],
             [3, 11],
             [3, 10],
             [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [6]:
#найдите среднее значение по каждому признаку, используя метод mean массива Numpy.
#Результат запишите в массив mean_a, в нем должно быть 2 элемента.
mean_a = a.mean(axis=0)
print(f'среднее значение: {mean_a}')

среднее значение: [2.  8.4]


In [14]:
#2 Вычислите массив a_centered, отняв от значений массива а 
#средние значения соответствующих признаков, содержащиеся в массиве mean_a.
#Вычисление должно производиться в одно действие.
#Получившийся массив должен иметь размер 5x2.
a_centered = np.subtract(a, mean_a)
#a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [16]:
#3. Найдите скалярное произведение столбцов массива a_centered.
#В результате должна получиться величина a_centered_sp. 
a1 = a_centered[:,0]
a2 = a_centered[:,1]
a_centered_sp = np.dot(a1,a2)
#a_centered_sp = a1.dot(a2)
a_centered_sp

8.0

In [20]:
#поделите a_centered_sp на N-1, где N - число наблюдений
N=a.shape[0]
N

5

In [21]:
my_cov=a_centered_sp/(N-1)
my_cov

2.0

In [26]:
#проверьте получившееся число, вычислив
#ковариацию еще одним способом — с помощью функции np.cov
np.cov(a.transpose())

array([[1. , 2. ],
       [2. , 4.3]])

In [25]:
#В получившейся ковариационной матрице (массив Numpy размером 2x2) 
#искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.
cov_2 = np.cov(a.transpose())[0,1]
cov_2

2.0